-- Switch the Upselling & Cross-Selling Growth Bonus ladder from rate-based
-- tiers (share of delivered orders touched by an upsell/cross-sell) to
-- profit-based tiers (contribution profit those upsells/cross-sells actually
-- generated this week). Bright: the bigger the profit, the bigger the
-- payout should be directly - the old rate-based ladder didn't guarantee
-- that. The Delivered Sales Expansion Rate stays on the dashboard as a
-- coaching metric, it just no longer decides the tier or the payout.

alter table public.upsell_bonus_settings
  alter column expansion_rate_tiers set default '[
    {"id":"tier-50k","label":"₦0 - ₦49,999","minProfit":0,"maxProfit":49999,"amount":5000},
    {"id":"tier-100k","label":"₦50,000 - ₦99,999","minProfit":50000,"maxProfit":99999,"amount":10000},
    {"id":"tier-150k","label":"₦100,000 - ₦149,999","minProfit":100000,"maxProfit":149999,"amount":15000},
    {"id":"tier-200k","label":"₦150,000 - ₦199,999","minProfit":150000,"maxProfit":199999,"amount":20000},
    {"id":"tier-200k-plus","label":"₦200,000+","minProfit":200000,"maxProfit":null,"amount":25000}
  ]'::jsonb,
  alter column gates_met_message set default 'Both gates are met - payout follows the contribution profit generated by qualifying upgrades/cross-sells this week, capped at a share of that same profit.',
  alter column below_tier_message set default 'Both gates are met, but this week''s contribution profit from qualifying upgrades/cross-sells is below the first bonus tier.',
  alter column description set default 'Rewards the manager for the contribution profit generated by verified upsells, package upgrades, and cross-sells - gated on its own profit and delivery-rate floors, and capped so the bonus can never exceed a share of that same profit.';

-- Backfill every row still holding the pre-existing default text/tiers
-- (i.e. no org has customized it away from the original rate-based ladder
-- yet, confirmed by inspecting the live table before writing this
-- migration) so today's live setting matches the new mechanism instead of
-- silently keeping stale rate-based tiers that the app no longer evaluates
-- the same way.
update public.upsell_bonus_settings
set
  expansion_rate_tiers = '[
    {"id":"tier-50k","label":"₦0 - ₦49,999","minProfit":0,"maxProfit":49999,"amount":5000},
    {"id":"tier-100k","label":"₦50,000 - ₦99,999","minProfit":50000,"maxProfit":99999,"amount":10000},
    {"id":"tier-150k","label":"₦100,000 - ₦149,999","minProfit":100000,"maxProfit":149999,"amount":15000},
    {"id":"tier-200k","label":"₦150,000 - ₦199,999","minProfit":150000,"maxProfit":199999,"amount":20000},
    {"id":"tier-200k-plus","label":"₦200,000+","minProfit":200000,"maxProfit":null,"amount":25000}
  ]'::jsonb,
  gates_met_message = 'Both gates are met - payout follows the contribution profit generated by qualifying upgrades/cross-sells this week, capped at a share of that same profit.',
  below_tier_message = 'Both gates are met, but this week''s contribution profit from qualifying upgrades/cross-sells is below the first bonus tier.',
  description = 'Rewards the manager for the contribution profit generated by verified upsells, package upgrades, and cross-sells - gated on its own profit and delivery-rate floors, and capped so the bonus can never exceed a share of that same profit.'
where gates_met_message = 'Both gates are met - payout follows the Delivered Sales Expansion Rate, capped at a share of real contribution profit.';
